package sr.math.behavior;

/*Generated by MPS */


public class Abs_BehaviorDescriptor extends MathExpression_BehaviorDescriptor {
  public Abs_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.math.structure.Abs";
  }
}
