package sr.math.behavior;

/*Generated by MPS */


public class Exp_BehaviorDescriptor extends MathExpression_BehaviorDescriptor {
  public Exp_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.math.structure.Exp";
  }
}
