package sr.math.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class MathExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public MathExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.math.structure.MathExpression";
  }
}
