package sr.functionblocks.interpreter;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import java.util.Set;
import java.util.HashSet;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;
import jetbrains.mps.smodel.SReference;
import jetbrains.mps.smodel.SModelReference;
import jetbrains.mps.smodel.SNodeId;

public class TypeHelper {
  public TypeHelper() {
  }

  public static SNode boxedType(SNode unboxed) {
    if (SNodeOperations.isInstanceOf(unboxed, "jetbrains.mps.baseLanguage.structure.DoubleType")) {
      return new TypeHelper.QuotationClass_1zzb2s_a0a0a0a().createNode();
    }
    if (SNodeOperations.isInstanceOf(unboxed, "jetbrains.mps.baseLanguage.structure.IntegerType")) {
      return new TypeHelper.QuotationClass_1zzb2s_a0a0b0a().createNode();
    }
    return unboxed;
  }

  public static class QuotationClass_1zzb2s_a0a0a0a {
    public QuotationClass_1zzb2s_a0a0a0a() {
    }

    public SNode createNode() {
      SNode result = null;
      Set<SNode> _parameterValues_129834374 = new HashSet<SNode>();
      SNode quotedNode_1 = null;
      {
        quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.ClassifierType", null, GlobalScope.getInstance(), false);
        SNode quotedNode1_2 = quotedNode_1;
        quotedNode1_2.addReference(SReference.create("classifier", quotedNode1_2, SModelReference.fromString("f:java_stub#6354ebe7-c22a-4a0f-ac54-50b52ab9b065#java.lang(JDK/java.lang@java_stub)"), SNodeId.fromString("~Double")));
        result = quotedNode1_2;
      }
      return result;
    }
  }

  public static class QuotationClass_1zzb2s_a0a0b0a {
    public QuotationClass_1zzb2s_a0a0b0a() {
    }

    public SNode createNode() {
      SNode result = null;
      Set<SNode> _parameterValues_129834374 = new HashSet<SNode>();
      SNode quotedNode_1 = null;
      {
        quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.ClassifierType", null, GlobalScope.getInstance(), false);
        SNode quotedNode1_2 = quotedNode_1;
        quotedNode1_2.addReference(SReference.create("classifier", quotedNode1_2, SModelReference.fromString("f:java_stub#6354ebe7-c22a-4a0f-ac54-50b52ab9b065#java.lang(JDK/java.lang@java_stub)"), SNodeId.fromString("~Integer")));
        result = quotedNode1_2;
      }
      return result;
    }
  }
}
