package jetbrains.mps.baselanguage.dispatch.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"jetbrains.mps.baselanguage.dispatch.structure.DispatchCase", "jetbrains.mps.baselanguage.dispatch.structure.DispatchExpression", "jetbrains.mps.baselanguage.dispatch.structure.DispatchedElementRef"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 1:
        return new DispatchExpression_BehaviorDescriptor();
      case 0:
        return new DispatchCase_BehaviorDescriptor();
      case 2:
        return new DispatchedElementRef_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
