package jetbrains.mps.baselanguage.dispatch.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class DispatchExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public DispatchExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.baselanguage.dispatch.structure.DispatchExpression";
  }
}
