package jetbrains.mps.baselanguage.dispatch.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class DispatchCase_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public DispatchCase_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.baselanguage.dispatch.structure.DispatchCase";
  }
}
