package jetbrains.mps.baselanguage.dispatch.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class DispatchedElementRef_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public DispatchedElementRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.baselanguage.dispatch.structure.DispatchedElementRef";
  }
}
