package jetbrains.mps.baselanguage.dispatch.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class DispatchedElementRef extends Expression {
  public static final String concept = "jetbrains.mps.baselanguage.dispatch.structure.DispatchedElementRef";

  public DispatchedElementRef(SNode node) {
    super(node);
  }

  public static DispatchedElementRef newInstance(SModel sm, boolean init) {
    return (DispatchedElementRef) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baselanguage.dispatch.structure.DispatchedElementRef", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static DispatchedElementRef newInstance(SModel sm) {
    return DispatchedElementRef.newInstance(sm, false);
  }
}
