package sr.functionblocks.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.ClassConcept;

public class BlockImportAnnotation_AnnotationLink {
  public static final String BLOCK_IMPORT_ANNOTATION = "blockImportAnnotation";

  public static void setBlockImportAnnotation(ClassConcept source, BlockImport target) {
    source.setAttribute(BlockImportAnnotation_AnnotationLink.BLOCK_IMPORT_ANNOTATION, target);
  }

  public static BlockImport getBlockImportAnnotation(ClassConcept source) {
    return (BlockImport) source.getAttribute(BlockImportAnnotation_AnnotationLink.BLOCK_IMPORT_ANNOTATION);
  }
}
