package sr.functionblocks.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.lang.core.structure.Attribute;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Documentation extends BaseConcept implements IBlockContent {
  public static final String concept = "sr.functionblocks.structure.Documentation";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String LINES = "lines";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public Documentation(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(Documentation.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Documentation.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Documentation.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Documentation.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Documentation.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Documentation.VIRTUAL_PACKAGE, value);
  }

  public int getLinesesCount() {
    return this.getChildCount(Documentation.LINES);
  }

  public Iterator<IDocContent> lineses() {
    return this.children(IDocContent.class, Documentation.LINES);
  }

  public List<IDocContent> getLineses() {
    return this.getChildren(IDocContent.class, Documentation.LINES);
  }

  public void addLines(IDocContent node) {
    this.addChild(Documentation.LINES, node);
  }

  public void insertLines(IDocContent prev, IDocContent node) {
    this.insertChild(prev, Documentation.LINES, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(Documentation.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, Documentation.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, Documentation.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(Documentation.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, Documentation.SMODEL_ATTRIBUTE, node);
  }

  public static Documentation newInstance(SModel sm, boolean init) {
    return (Documentation) SModelUtil_new.instantiateConceptDeclaration("sr.functionblocks.structure.Documentation", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Documentation newInstance(SModel sm) {
    return Documentation.newInstance(sm, false);
  }
}
