package sr.functionblocks.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class EnvBlock extends Block {
  public static final String concept = "sr.functionblocks.structure.EnvBlock";

  public EnvBlock(SNode node) {
    super(node);
  }

  public static EnvBlock newInstance(SModel sm, boolean init) {
    return (EnvBlock) SModelUtil_new.instantiateConceptDeclaration("sr.functionblocks.structure.EnvBlock", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static EnvBlock newInstance(SModel sm) {
    return EnvBlock.newInstance(sm, false);
  }
}
