package sr.functionblocks.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ErrorMarker extends BaseConcept {
  public static final String concept = "sr.functionblocks.structure.ErrorMarker";
  public static final String ERROR_MESSAGE = "errorMessage";

  public ErrorMarker(SNode node) {
    super(node);
  }

  public String getErrorMessage() {
    return this.getProperty(ErrorMarker.ERROR_MESSAGE);
  }

  public void setErrorMessage(String value) {
    this.setProperty(ErrorMarker.ERROR_MESSAGE, value);
  }

  public static ErrorMarker newInstance(SModel sm, boolean init) {
    return (ErrorMarker) SModelUtil_new.instantiateConceptDeclaration("sr.functionblocks.structure.ErrorMarker", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ErrorMarker newInstance(SModel sm) {
    return ErrorMarker.newInstance(sm, false);
  }
}
