package sr.functionblocks.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class FunctionSymbolExpressionWrapper extends BaseConcept {
  public static final String concept = "sr.functionblocks.structure.FunctionSymbolExpressionWrapper";
  public static final String EXPRESSION = "expression";

  public FunctionSymbolExpressionWrapper(SNode node) {
    super(node);
  }

  public Expression getExpression() {
    return (Expression) this.getChild(Expression.class, FunctionSymbolExpressionWrapper.EXPRESSION);
  }

  public void setExpression(Expression node) {
    super.setChild(FunctionSymbolExpressionWrapper.EXPRESSION, node);
  }

  public static FunctionSymbolExpressionWrapper newInstance(SModel sm, boolean init) {
    return (FunctionSymbolExpressionWrapper) SModelUtil_new.instantiateConceptDeclaration("sr.functionblocks.structure.FunctionSymbolExpressionWrapper", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static FunctionSymbolExpressionWrapper newInstance(SModel sm) {
    return FunctionSymbolExpressionWrapper.newInstance(sm, false);
  }
}
