package sr.functionblocks.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface IBlockContent extends INodeAdapter {
  public static final String concept = "sr.functionblocks.structure.IBlockContent";
}
