package sr.functionblocks.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface IDocContent extends INodeAdapter {
  public static final String concept = "sr.functionblocks.structure.IDocContent";
}
