package sr.functionblocks.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class JVSReference extends BaseConcept {
  public static final String concept = "sr.functionblocks.structure.JVSReference";
  public static final String VALUE_SET = "valueSet";

  public JVSReference(SNode node) {
    super(node);
  }

  public JValueSet getValueSet() {
    return (JValueSet) this.getReferent(JValueSet.class, JVSReference.VALUE_SET);
  }

  public void setValueSet(JValueSet node) {
    super.setReferent(JVSReference.VALUE_SET, node);
  }

  public static JVSReference newInstance(SModel sm, boolean init) {
    return (JVSReference) SModelUtil_new.instantiateConceptDeclaration("sr.functionblocks.structure.JVSReference", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static JVSReference newInstance(SModel sm) {
    return JVSReference.newInstance(sm, false);
  }
}
