package sr.functionblocks.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.baseLanguage.structure.IValidIdentifier;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.lang.core.structure.Attribute;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PDFDocStructure extends BaseConcept implements IValidIdentifier {
  public static final String concept = "sr.functionblocks.structure.PDFDocStructure";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String BLOCKS = "blocks";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public PDFDocStructure(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(PDFDocStructure.NAME);
  }

  public void setName(String value) {
    this.setProperty(PDFDocStructure.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(PDFDocStructure.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(PDFDocStructure.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(PDFDocStructure.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(PDFDocStructure.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(PDFDocStructure.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(PDFDocStructure.VIRTUAL_PACKAGE, value);
  }

  public int getBlocksesCount() {
    return this.getChildCount(PDFDocStructure.BLOCKS);
  }

  public Iterator<BlockReference> blockses() {
    return this.children(BlockReference.class, PDFDocStructure.BLOCKS);
  }

  public List<BlockReference> getBlockses() {
    return this.getChildren(BlockReference.class, PDFDocStructure.BLOCKS);
  }

  public void addBlocks(BlockReference node) {
    this.addChild(PDFDocStructure.BLOCKS, node);
  }

  public void insertBlocks(BlockReference prev, BlockReference node) {
    this.insertChild(prev, PDFDocStructure.BLOCKS, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(PDFDocStructure.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, PDFDocStructure.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, PDFDocStructure.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(PDFDocStructure.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, PDFDocStructure.SMODEL_ATTRIBUTE, node);
  }

  public static PDFDocStructure newInstance(SModel sm, boolean init) {
    return (PDFDocStructure) SModelUtil_new.instantiateConceptDeclaration("sr.functionblocks.structure.PDFDocStructure", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static PDFDocStructure newInstance(SModel sm) {
    return PDFDocStructure.newInstance(sm, false);
  }
}
