package sr.functionblocks.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SymbolReference extends Expression implements IDocContent {
  public static final String concept = "sr.functionblocks.structure.SymbolReference";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SYMBOL = "symbol";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public SymbolReference(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(SymbolReference.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(SymbolReference.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(SymbolReference.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(SymbolReference.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(SymbolReference.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(SymbolReference.VIRTUAL_PACKAGE, value);
  }

  public Symbol getSymbol() {
    return (Symbol) this.getReferent(Symbol.class, SymbolReference.SYMBOL);
  }

  public void setSymbol(Symbol node) {
    super.setReferent(SymbolReference.SYMBOL, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(SymbolReference.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, SymbolReference.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, SymbolReference.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(SymbolReference.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, SymbolReference.SMODEL_ATTRIBUTE, node);
  }

  public static SymbolReference newInstance(SModel sm, boolean init) {
    return (SymbolReference) SModelUtil_new.instantiateConceptDeclaration("sr.functionblocks.structure.SymbolReference", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SymbolReference newInstance(SModel sm) {
    return SymbolReference.newInstance(sm, false);
  }
}
