package sr.math.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilders;
import jetbrains.mps.lang.dataFlow.DataFlowManager;

public class DFABuilders extends DataFlowBuilders {
  public void install(DataFlowManager manager) {
    manager.register("sr.math.structure.Abs", new Abs_DataFlow());
    manager.register("sr.math.structure.Exp", new Exp_DataFlow());
  }
}
