package sr.math.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.typesystem.inference.EquationInfo;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.SModelUtil_new;

public class typeof_Exp_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_Exp_InferenceRule() {
  }

  public void applyRule(final SNode exp, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      SNode _nodeToCheck_1029348928467 = exp;
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:526b1701-42e5-4ace-bfca-3c8daa5e9193(sr.math.typesystem)", "5279185967172092775", 0, null);
      typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:526b1701-42e5-4ace-bfca-3c8daa5e9193(sr.math.typesystem)", "5279185967172092772", true), (SNode) typeCheckingContext.typeOf(SLinkOperations.getTarget(exp, "base", true), "r:526b1701-42e5-4ace-bfca-3c8daa5e9193(sr.math.typesystem)", "5279185967172092780", true), _info_12389875345);
    }
  }

  public String getApplicableConceptFQName() {
    return "sr.math.structure.Exp";
  }

  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    {
      boolean b = SModelUtil_new.isAssignableConcept(argument.getConceptFqName(), this.getApplicableConceptFQName());
      return new IsApplicableStatus(b, null);
    }
  }

  public boolean overrides() {
    return false;
  }
}
