package sr.si.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"sr.si.structure.CompositeUnit", "sr.si.structure.CompositeUnitFraction", "sr.si.structure.ForceUnit", "sr.si.structure.Hecto", "sr.si.structure.Kilo", "sr.si.structure.KiloGramm", "sr.si.structure.Meter", "sr.si.structure.Newton", "sr.si.structure.NoUnit", "sr.si.structure.Pascal", "sr.si.structure.PressureUnit", "sr.si.structure.Second"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 6:
        return new Meter_BehaviorDescriptor();
      case 4:
        return new Kilo_BehaviorDescriptor();
      case 1:
        return new CompositeUnitFraction_BehaviorDescriptor();
      case 0:
        return new CompositeUnit_BehaviorDescriptor();
      case 3:
        return new Hecto_BehaviorDescriptor();
      case 8:
        return new NoUnit_BehaviorDescriptor();
      case 11:
        return new Second_BehaviorDescriptor();
      case 9:
        return new Pascal_BehaviorDescriptor();
      case 10:
        return new PressureUnit_BehaviorDescriptor();
      case 7:
        return new Newton_BehaviorDescriptor();
      case 2:
        return new ForceUnit_BehaviorDescriptor();
      case 5:
        return new KiloGramm_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
