package sr.si.behavior;

/*Generated by MPS */

import sr.si.rt.InternalCompositeUnit;
import jetbrains.mps.smodel.SNode;

public class CompositeUnitFraction_BehaviorDescriptor extends Unit_BehaviorDescriptor {
  public CompositeUnitFraction_BehaviorDescriptor() {
  }

  public InternalCompositeUnit virtual_toInternal_1525172282798172010(SNode thisNode) {
    return CompositeUnitFraction_Behavior.virtual_toInternal_1525172282798172010(thisNode);
  }

  public String virtual_toString_7203693294560873740(SNode thisNode) {
    return CompositeUnitFraction_Behavior.virtual_toString_7203693294560873740(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "sr.si.structure.CompositeUnitFraction";
  }
}
