package sr.si.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import sr.si.rt.InternalCompositeUnit;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.IVisitor;

public class CompositeUnit_Behavior {
  public static void init(SNode thisNode) {
  }

  public static InternalCompositeUnit virtual_toInternal_1525172282798172010(SNode thisNode) {
    InternalCompositeUnit res = new InternalCompositeUnit();
    for (SNode u : ListSequence.fromList(SLinkOperations.getTargets(thisNode, "factors", true))) {
      res = res.add(Unit_Behavior.call_toInternal_1525172282798172010(u), 1);
    }
    return res;
  }

  public static String virtual_toString_7203693294560873740(SNode thisNode) {
    final StringBuffer bf = new StringBuffer();
    bf.append("(");
    ListSequence.fromList(SLinkOperations.getTargets(thisNode, "factors", true)).visitAll(new IVisitor<SNode>() {
      public void visit(SNode it) {
        bf.append(Unit_Behavior.call_toString_7203693294560873740(it) + " ");
      }
    });
    bf.append(")");
    return bf.toString();
  }
}
