package sr.si.behavior;

/*Generated by MPS */

import sr.si.rt.InternalCompositeUnit;
import jetbrains.mps.smodel.SNode;

public class CompositeUnit_BehaviorDescriptor extends Unit_BehaviorDescriptor {
  public CompositeUnit_BehaviorDescriptor() {
  }

  public InternalCompositeUnit virtual_toInternal_1525172282798172010(SNode thisNode) {
    return CompositeUnit_Behavior.virtual_toInternal_1525172282798172010(thisNode);
  }

  public String virtual_toString_7203693294560873740(SNode thisNode) {
    return CompositeUnit_Behavior.virtual_toString_7203693294560873740(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "sr.si.structure.CompositeUnit";
  }
}
