package sr.si.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import sr.si.rt.InternalCompositeUnit;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class CompositeUnitFraction_Behavior {
  public static void init(SNode thisNode) {
  }

  public static InternalCompositeUnit virtual_toInternal_1525172282798172010(SNode thisNode) {
    return new InternalCompositeUnit().add(Unit_Behavior.call_toInternal_1525172282798172010(SLinkOperations.getTarget(thisNode, "numerator", true))).add(Unit_Behavior.call_toInternal_1525172282798172010(SLinkOperations.getTarget(thisNode, "denominator", true)).inverse());
  }

  public static String virtual_toString_7203693294560873740(SNode thisNode) {
    StringBuffer bf = new StringBuffer();
    bf.append(Unit_Behavior.call_toString_7203693294560873740(SLinkOperations.getTarget(thisNode, "numerator", true)));
    bf.append(" / ");
    bf.append(Unit_Behavior.call_toString_7203693294560873740(SLinkOperations.getTarget(thisNode, "denominator", true)));
    return bf.toString();
  }
}
