package sr.si.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Factor_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Factor_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.si.structure.Factor";
  }
}
