package sr.si.behavior;

/*Generated by MPS */


public class ForceUnit_BehaviorDescriptor extends Unit_BehaviorDescriptor {
  public ForceUnit_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.si.structure.ForceUnit";
  }
}
