package sr.si.behavior;

/*Generated by MPS */


public class Hecto_BehaviorDescriptor extends Factor_BehaviorDescriptor {
  public Hecto_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.si.structure.Hecto";
  }
}
