package sr.si.behavior;

/*Generated by MPS */


public class KiloGramm_BehaviorDescriptor extends WeightUnit_BehaviorDescriptor {
  public KiloGramm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.si.structure.KiloGramm";
  }
}
