package sr.si.behavior;

/*Generated by MPS */


public class Kilo_BehaviorDescriptor extends Factor_BehaviorDescriptor {
  public Kilo_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.si.structure.Kilo";
  }
}
