package sr.si.behavior;

/*Generated by MPS */


public abstract class LengthUnit_BehaviorDescriptor extends Unit_BehaviorDescriptor {
  public LengthUnit_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.si.structure.LengthUnit";
  }
}
