package sr.si.behavior;

/*Generated by MPS */


public class Meter_BehaviorDescriptor extends LengthUnit_BehaviorDescriptor {
  public Meter_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.si.structure.Meter";
  }
}
