package sr.si.behavior;

/*Generated by MPS */


public class Newton_BehaviorDescriptor extends ForceUnit_BehaviorDescriptor implements IReducableUnit_BehaviorDescriptor {
  public Newton_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.si.structure.Newton";
  }
}
