package sr.si.behavior;

/*Generated by MPS */


public class NoUnit_BehaviorDescriptor extends Unit_BehaviorDescriptor {
  public NoUnit_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.si.structure.NoUnit";
  }
}
