package sr.si.behavior;

/*Generated by MPS */


public class Pascal_BehaviorDescriptor extends PressureUnit_BehaviorDescriptor implements IReducableUnit_BehaviorDescriptor {
  public Pascal_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.si.structure.Pascal";
  }
}
