package sr.si.behavior;

/*Generated by MPS */


public class PressureUnit_BehaviorDescriptor extends Unit_BehaviorDescriptor {
  public PressureUnit_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.si.structure.PressureUnit";
  }
}
