package sr.si.behavior;

/*Generated by MPS */


public class Second_BehaviorDescriptor extends TimeUnit_BehaviorDescriptor {
  public Second_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.si.structure.Second";
  }
}
