package sr.si.behavior;

/*Generated by MPS */


public abstract class TimeUnit_BehaviorDescriptor extends Unit_BehaviorDescriptor {
  public TimeUnit_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.si.structure.TimeUnit";
  }
}
