package sr.si.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import sr.si.rt.InternalCompositeUnit;
import jetbrains.mps.smodel.SNode;

public abstract class Unit_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Unit_BehaviorDescriptor() {
  }

  public InternalCompositeUnit virtual_toInternal_1525172282798172010(SNode thisNode) {
    return Unit_Behavior.virtual_toInternal_1525172282798172010(thisNode);
  }

  public String virtual_toString_7203693294560873740(SNode thisNode) {
    return Unit_Behavior.virtual_toString_7203693294560873740(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "sr.si.structure.Unit";
  }
}
