package sr.si.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import sr.si.rt.InternalCompositeUnit;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.structure.BehaviorDescriptor;
import jetbrains.mps.smodel.structure.ConceptRegistry;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

public class Unit_Behavior {
  private static Class[] PARAMETERS_1525172282798172010 = {SNode.class};
  private static Class[] PARAMETERS_7203693294560873740 = {SNode.class};

  public static void init(SNode thisNode) {
  }

  public static InternalCompositeUnit virtual_toInternal_1525172282798172010(SNode thisNode) {
    InternalCompositeUnit unit = new InternalCompositeUnit();
    if (SNodeOperations.isInstanceOf(thisNode, "sr.si.structure.IReducableUnit")) {
      return Unit_Behavior.call_toInternal_1525172282798172010(ListSequence.fromList(SLinkOperations.getConceptLinkTargets(SNodeOperations.cast(thisNode, "sr.si.structure.IReducableUnit"), "reduction")).first());
    }
    unit.addInternal(SNodeOperations.getConceptDeclaration(thisNode), 1);
    return unit;
  }

  public static String virtual_toString_7203693294560873740(SNode thisNode) {
    return SPropertyOperations.getString(SNodeOperations.getConceptDeclaration(thisNode), "name");
  }

  public static InternalCompositeUnit call_toInternal_1525172282798172010(SNode thisNode) {
    BehaviorDescriptor descriptor = ConceptRegistry.getInstance().getBehaviorDescriptorForInstanceNode(thisNode);
    return (InternalCompositeUnit) descriptor.invoke(Object.class, SNodeOperations.cast(thisNode, "sr.si.structure.Unit"), "virtual_toInternal_1525172282798172010", PARAMETERS_1525172282798172010);
  }

  public static String call_toString_7203693294560873740(SNode thisNode) {
    BehaviorDescriptor descriptor = ConceptRegistry.getInstance().getBehaviorDescriptorForInstanceNode(thisNode);
    return (String) descriptor.invoke(Object.class, SNodeOperations.cast(thisNode, "sr.si.structure.Unit"), "virtual_toString_7203693294560873740", PARAMETERS_7203693294560873740);
  }

  public static InternalCompositeUnit callSuper_toInternal_1525172282798172010(SNode thisNode, String callerConceptFqName) {
    return (InternalCompositeUnit) BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "sr.si.structure.Unit"), callerConceptFqName, "virtual_toInternal_1525172282798172010", PARAMETERS_1525172282798172010);
  }

  public static String callSuper_toString_7203693294560873740(SNode thisNode, String callerConceptFqName) {
    return (String) BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "sr.si.structure.Unit"), callerConceptFqName, "virtual_toString_7203693294560873740", PARAMETERS_7203693294560873740);
  }
}
