package sr.si.behavior;

/*Generated by MPS */


public abstract class WeightUnit_BehaviorDescriptor extends Unit_BehaviorDescriptor {
  public WeightUnit_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.si.structure.WeightUnit";
  }
}
