package aero;

/*Generated by MPS */

import sr.functionblocks.rt.main.ValueSetContainer;
import sr.functionblocks.rt.main.Value;
import sr.functionblocks.rt.main.TestFailedException;

public class TestClass {
  public TestClass() {
  }

  public void calcLift() {
    ValueSetContainer air = new ValueSetContainer(new Value("Environment_rho", 1.225));
    ValueSetContainer planeStatic = new ValueSetContainer(new Value("Aircraft_A", 10.0), new Value("Aircraft_c_a", 0.5), new Value("Aircraft_c_w", 0.3));
    for (int i = 0; i < 100; i++) {
      ValueSetContainer planeDynamic = new ValueSetContainer(new Value("Aircraft_v", (double) i * 1.1));
      double lift = new StuffontheWings_Implementation().F_A(air, planeStatic, planeDynamic);
      System.err.println(i + "->" + lift);
    }
  }

  public static void main(String[] args) {
    try {
      new FundamentalStuff_Implementation().runTests();
    } catch (TestFailedException ex) {
      System.err.println("tests failed for block " + "Fundamental Stuff");
      ex.printStackTrace();
    }
    try {
      new StuffontheWings_Implementation().runTests();
    } catch (TestFailedException ex) {
      System.err.println("tests failed for block " + "Stuff on the Wings");
      ex.printStackTrace();
    }
    new TestClass().calcLift();
  }
}
