package sr.functionblocks.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.SModelReference;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("sr.functionblocks", "2faf624a-e752-4c54-81e5-c37af7a91129"), SModelReference.fromString("r:449db549-4842-44e0-b1a7-2c6e1f4ac084(sr.functionblocks.intentions)"));
  }

  public void init() {
    add(new addBlockImport_Intention(), "3006277004735749129");
    add(new hideAllTests_Intention(), "7691223970093200800");
    add(new toggleExport_Intention(), "7691223970092892472");
    add(new toggleTests_Intention(), "7691223970093125892");
  }
}
