package sr.functionblocks.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntention;
import jetbrains.mps.intentions.Intention;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class toggleExport_Intention extends BaseIntention implements Intention {
  public toggleExport_Intention() {
  }

  public String getConcept() {
    return "sr.functionblocks.structure.FunctionSymbol";
  }

  public boolean isParameterized() {
    return false;
  }

  public boolean isErrorIntention() {
    return false;
  }

  public boolean isAvailableInChildNodes() {
    return true;
  }

  public String getDescription(final SNode node, final EditorContext editorContext) {
    return "toggle export";
  }

  public void execute(final SNode node, final EditorContext editorContext) {
    SPropertyOperations.set(node, "exported", "" + !(SPropertyOperations.getBoolean(node, "exported")));
  }

  public String getLocationString() {
    return "sr.functionblocks.intentions";
  }
}
