package sr.functionblocks.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntention;
import jetbrains.mps.intentions.Intention;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class toggleTests_Intention extends BaseIntention implements Intention {
  public toggleTests_Intention() {
  }

  public String getConcept() {
    return "sr.functionblocks.structure.FunctionSymbol";
  }

  public boolean isParameterized() {
    return false;
  }

  public boolean isErrorIntention() {
    return false;
  }

  public boolean isAvailableInChildNodes() {
    return true;
  }

  public String getDescription(final SNode node, final EditorContext editorContext) {
    return "toggle tests";
  }

  public void execute(final SNode node, final EditorContext editorContext) {
    if (SLinkOperations.getTarget(node, "testBlock", true) == null) {
      SNodeFactoryOperations.setNewChild(node, "testBlock", "sr.functionblocks.structure.FunctionUnitTestBlock");
      SPropertyOperations.set(node, "showTests", "" + true);
    } else {
      SPropertyOperations.set(node, "showTests", "" + !(SPropertyOperations.getBoolean(node, "showTests")));
    }
  }

  public String getLocationString() {
    return "sr.functionblocks.intentions";
  }
}
