package sr.functionblocks.texgen.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import sr.functionblocks.texgen.generator.template.util.RenderingHelper;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import sr.functionblocks.behavior.PDFDocStructure_Behavior;
import sr.functionblocks.behavior.EnvBlock_Behavior;

public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_6490254263633871148(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SNodeOperations.cast(_context.getNode(), "sr.functionblocks.structure.Block"), "name");
  }

  public static Object propertyMacro_GetPropertyValue_4689918572531106952(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "$" + SPropertyOperations.getString(_context.getNode(), "name") + "$";
  }

  public static Object propertyMacro_GetPropertyValue_4689918572531106966(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return new RenderingHelper().unitToTex(SLinkOperations.getTarget(_context.getNode(), "unit", true));
  }

  public static Object propertyMacro_GetPropertyValue_4689918572531106983(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "javaType", true) + "";
  }

  public static Object propertyMacro_GetPropertyValue_4689918572531106994(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "description");
  }

  public static Object propertyMacro_GetPropertyValue_6490254263633959511(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SNodeOperations.cast(_context.getNode(), "sr.functionblocks.structure.Block"), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6490254263633842938(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6490254263633859617(final IOperationContext operationContext, final PropertyMacroContext _context) {
    if (SNodeOperations.isInstanceOf(_context.getNode(), "sr.functionblocks.structure.DocumentationText")) {
      return SPropertyOperations.getString(SNodeOperations.cast(_context.getNode(), "sr.functionblocks.structure.DocumentationText"), "text");
    } else if (SNodeOperations.isInstanceOf(_context.getNode(), "sr.functionblocks.structure.SymbolReference")) {
      return SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.cast(_context.getNode(), "sr.functionblocks.structure.SymbolReference"), "symbol", false), "name");
    } else {
      return "";
    }
  }

  public static Object propertyMacro_GetPropertyValue_4689918572531121783(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "$" + SPropertyOperations.getString(_context.getNode(), "name") + "$ \\hspace{1 mm} = \\hspace{1 mm}";
  }

  public static Object propertyMacro_GetPropertyValue_4689918572531121795(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "$" + new RenderingHelper().expressionToTex(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "expr", true), "expression", true)) + "$";
  }

  public static Object propertyMacro_GetPropertyValue_4689918572531124035(final IOperationContext operationContext, final PropertyMacroContext _context) {
    if (SNodeOperations.isInstanceOf(_context.getNode(), "sr.functionblocks.structure.DocumentationText")) {
      return SPropertyOperations.getString(SNodeOperations.cast(_context.getNode(), "sr.functionblocks.structure.DocumentationText"), "text");
    } else if (SNodeOperations.isInstanceOf(_context.getNode(), "sr.functionblocks.structure.SymbolReference")) {
      return "$" + SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.cast(_context.getNode(), "sr.functionblocks.structure.SymbolReference"), "symbol", false), "name") + "$";
    } else {
      return "";
    }
  }

  public static Iterable sourceNodesQuery_6490254263633851637(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return PDFDocStructure_Behavior.call_envblocks_6490254263633884937(_context.getNode());
  }

  public static Iterable sourceNodesQuery_4689918572531107008(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return EnvBlock_Behavior.call_envsymbols_6490254263633884628(_context.getNode());
  }

  public static Iterable sourceNodesQuery_6490254263633959501(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return PDFDocStructure_Behavior.call_funblocks_6490254263633959610(_context.getNode());
  }

  public static Iterable sourceNodesQuery_6490254263633993571(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "contents", true);
  }

  public static Iterable sourceNodesQuery_6490254263633859607(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "lines", true);
  }

  public static Iterable sourceNodesQuery_4689918572531124025(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "lines", true);
  }
}
