package sr.functionblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class BlockImportBlockRef_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public BlockImportBlockRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.functionblocks.structure.BlockImportBlockRef";
  }
}
