package sr.functionblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Documentation_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IBlockContent_BehaviorDescriptor {
  public Documentation_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.functionblocks.structure.Documentation";
  }
}
