package sr.functionblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class Documentation_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.addNewChild(thisNode, "lines", "sr.functionblocks.structure.DocumentationText");
  }
}
