package sr.functionblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class DocumentationText_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IDocContent_BehaviorDescriptor {
  public DocumentationText_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.functionblocks.structure.DocumentationText";
  }
}
