package sr.functionblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class EnvBlock_BehaviorDescriptor extends Block_BehaviorDescriptor {
  public EnvBlock_BehaviorDescriptor() {
  }

  public Iterable<SNode> virtual_exportedSymbols_7691223970092868586(SNode thisNode) {
    return EnvBlock_Behavior.virtual_exportedSymbols_7691223970092868586(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "sr.functionblocks.structure.EnvBlock";
  }
}
