package sr.functionblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import java.util.Set;
import java.util.HashSet;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class EnvSymbol_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.setTarget(thisNode, "javaType", new EnvSymbol_Behavior.QuotationClass_drsye_a2a0a0().createNode(), true);
    SLinkOperations.setTarget(thisNode, "unit", new EnvSymbol_Behavior.QuotationClass_drsye_a2a1a0().createNode(), true);
  }

  public static class QuotationClass_drsye_a2a0a0 {
    public QuotationClass_drsye_a2a0a0() {
    }

    public SNode createNode() {
      SNode result = null;
      Set<SNode> _parameterValues_129834374 = new HashSet<SNode>();
      SNode quotedNode_1 = null;
      {
        quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.DoubleType", null, GlobalScope.getInstance(), false);
        SNode quotedNode1_2 = quotedNode_1;
        result = quotedNode1_2;
      }
      return result;
    }
  }

  public static class QuotationClass_drsye_a2a1a0 {
    public QuotationClass_drsye_a2a1a0() {
    }

    public SNode createNode() {
      SNode result = null;
      Set<SNode> _parameterValues_129834374 = new HashSet<SNode>();
      SNode quotedNode_1 = null;
      {
        quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("sr.si.structure.NoUnit", null, GlobalScope.getInstance(), false);
        SNode quotedNode1_2 = quotedNode_1;
        result = quotedNode1_2;
      }
      return result;
    }
  }
}
