package sr.functionblocks.behavior;

/*Generated by MPS */


public class EnvSymbol_BehaviorDescriptor extends Symbol_BehaviorDescriptor {
  public EnvSymbol_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.functionblocks.structure.EnvSymbol";
  }
}
