package sr.functionblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class ErrorMarker_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ErrorMarker_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.functionblocks.structure.ErrorMarker";
  }
}
