package sr.functionblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class FunctionUnitTestBlock_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public FunctionUnitTestBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.functionblocks.structure.FunctionUnitTestBlock";
  }
}
