package sr.functionblocks.behavior;

/*Generated by MPS */


public class FunctionSymbol_BehaviorDescriptor extends Symbol_BehaviorDescriptor {
  public FunctionSymbol_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.functionblocks.structure.FunctionSymbol";
  }
}
