package sr.functionblocks.behavior;

/*Generated by MPS */


public class InternalInterpreterErrorMarker_BehaviorDescriptor extends ErrorMarker_BehaviorDescriptor {
  public InternalInterpreterErrorMarker_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.functionblocks.structure.InternalInterpreterErrorMarker";
  }
}
