package sr.functionblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import java.util.List;
import java.util.Set;
import jetbrains.mps.internal.collections.runtime.SetSequence;
import java.util.HashSet;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class JFunctionCall_Behavior {
  public static void init(SNode thisNode) {
  }

  public static List<SNode> call_requiredInputSymbols_3006277004735647967(SNode thisNode) {
    Set<SNode> result = SetSequence.fromSet(new HashSet<SNode>());
    FunctionSymbol_Behavior.call_collectReferencedEnvSymbols_3006277004735674310(SLinkOperations.getTarget(thisNode, "function", false), result);
    return SetSequence.fromSet(result).toListSequence();
  }
}
