package sr.functionblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class JFunctionCall_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public JFunctionCall_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.functionblocks.structure.JFunctionCall";
  }
}
