package sr.functionblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class JValueDefinition_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public JValueDefinition_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.functionblocks.structure.JValueDefinition";
  }
}
