package sr.functionblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ISelector;

public class PDFDocStructure_Behavior {
  public static void init(SNode thisNode) {
  }

  public static Iterable<SNode> call_envblocks_6490254263633884937(SNode thisNode) {
    return ListSequence.fromList(SLinkOperations.getTargets(thisNode, "blocks", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(it, "block", false), "sr.functionblocks.structure.EnvBlock");
      }
    }).select(new ISelector<SNode, SNode>() {
      public SNode select(SNode it) {
        return SNodeOperations.cast(SLinkOperations.getTarget(it, "block", false), "sr.functionblocks.structure.EnvBlock");
      }
    });
  }

  public static Iterable<SNode> call_funblocks_6490254263633959610(SNode thisNode) {
    return ListSequence.fromList(SLinkOperations.getTargets(thisNode, "blocks", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(it, "block", false), "sr.functionblocks.structure.FunctionBlock");
      }
    }).select(new ISelector<SNode, SNode>() {
      public SNode select(SNode it) {
        return SNodeOperations.cast(SLinkOperations.getTarget(it, "block", false), "sr.functionblocks.structure.FunctionBlock");
      }
    });
  }
}
