package sr.functionblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class RunTestsStatement_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public RunTestsStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.functionblocks.structure.RunTestsStatement";
  }
}
