package sr.functionblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class SymbolReference_BehaviorDescriptor extends Expression_BehaviorDescriptor implements IDocContent_BehaviorDescriptor {
  public SymbolReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.functionblocks.structure.SymbolReference";
  }
}
