package sr.functionblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class SymbolValue_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public SymbolValue_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "sr.functionblocks.structure.SymbolValue";
  }
}
