package jetbrains.mps.baselanguage.dispatch.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.SModelReference;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("jetbrains.mps.baselanguage.dispatch", "dcf3d20f-f3f9-4cf9-aa39-cbd6329f23c3"), SModelReference.fromString("r:fb0e7df2-bf0e-43db-8f12-bc2f81bb9884(jetbrains.mps.baselanguage.dispatch.intentions)"));
  }

  public void init() {
    add(new addBody_Intention(), "1525172282798157024");
  }
}
