package sr.math.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Abs extends MathExpression {
  public static final String concept = "sr.math.structure.Abs";
  public static final String EXPR = "expr";

  public Abs(SNode node) {
    super(node);
  }

  public Expression getExpr() {
    return (Expression) this.getChild(Expression.class, Abs.EXPR);
  }

  public void setExpr(Expression node) {
    super.setChild(Abs.EXPR, node);
  }

  public static Abs newInstance(SModel sm, boolean init) {
    return (Abs) SModelUtil_new.instantiateConceptDeclaration("sr.math.structure.Abs", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Abs newInstance(SModel sm) {
    return Abs.newInstance(sm, false);
  }
}
