package sr.math.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Math_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("625c9f11-a499-4d69-9d3f-27f487e0b4f1(sr.math)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
