package sr.math.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class MathExpression extends Expression {
  public static final String concept = "sr.math.structure.MathExpression";

  public MathExpression(SNode node) {
    super(node);
  }

  public static MathExpression newInstance(SModel sm, boolean init) {
    return (MathExpression) SModelUtil_new.instantiateConceptDeclaration("sr.math.structure.MathExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static MathExpression newInstance(SModel sm) {
    return MathExpression.newInstance(sm, false);
  }
}
