package sr.math.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.CompiledConceptDescriptor;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  private static String[] stringSwitchCases_1htk8d_a0a0a = new String[]{"sr.math.structure.Abs", "sr.math.structure.Exp", "sr.math.structure.MathExpression"};

  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0a, conceptFqName)) {
      case 0:
        return new CompiledConceptDescriptor("sr.math.structure.Abs", "sr.math.structure.MathExpression", false, new String[]{"sr.math.structure.MathExpression"}, new String[]{}, new String[]{});
      case 1:
        return new CompiledConceptDescriptor("sr.math.structure.Exp", "sr.math.structure.MathExpression", false, new String[]{"sr.math.structure.MathExpression"}, new String[]{}, new String[]{});
      case 2:
        return new CompiledConceptDescriptor("sr.math.structure.MathExpression", "jetbrains.mps.baseLanguage.structure.Expression", false, new String[]{"jetbrains.mps.baseLanguage.structure.Expression"}, new String[]{}, new String[]{});
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }
}
