package sr.si.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CompositeUnitFraction extends Unit {
  public static final String concept = "sr.si.structure.CompositeUnitFraction";
  public static final String DENOMINATOR = "denominator";
  public static final String NUMERATOR = "numerator";

  public CompositeUnitFraction(SNode node) {
    super(node);
  }

  public CompositeUnit getDenominator() {
    return (CompositeUnit) this.getChild(CompositeUnit.class, CompositeUnitFraction.DENOMINATOR);
  }

  public void setDenominator(CompositeUnit node) {
    super.setChild(CompositeUnitFraction.DENOMINATOR, node);
  }

  public CompositeUnit getNumerator() {
    return (CompositeUnit) this.getChild(CompositeUnit.class, CompositeUnitFraction.NUMERATOR);
  }

  public void setNumerator(CompositeUnit node) {
    super.setChild(CompositeUnitFraction.NUMERATOR, node);
  }

  public static CompositeUnitFraction newInstance(SModel sm, boolean init) {
    return (CompositeUnitFraction) SModelUtil_new.instantiateConceptDeclaration("sr.si.structure.CompositeUnitFraction", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CompositeUnitFraction newInstance(SModel sm) {
    return CompositeUnitFraction.newInstance(sm, false);
  }
}
