package sr.si.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Factor extends BaseConcept {
  public static final String concept = "sr.si.structure.Factor";
  public static final String CPR_Factor = "factor";

  public Factor(SNode node) {
    super(node);
  }

  public static Factor newInstance(SModel sm, boolean init) {
    return (Factor) SModelUtil_new.instantiateConceptDeclaration("sr.si.structure.Factor", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Factor newInstance(SModel sm) {
    return Factor.newInstance(sm, false);
  }
}
