package sr.si.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface IReducableUnit extends INodeAdapter {
  public static final String concept = "sr.si.structure.IReducableUnit";
  public static String CLNK_Reduction = "reduction";
}
