package sr.si.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Kilo extends Factor {
  public static final String concept = "sr.si.structure.Kilo";

  public Kilo(SNode node) {
    super(node);
  }

  public static Kilo newInstance(SModel sm, boolean init) {
    return (Kilo) SModelUtil_new.instantiateConceptDeclaration("sr.si.structure.Kilo", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Kilo newInstance(SModel sm) {
    return Kilo.newInstance(sm, false);
  }
}
