package sr.si.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class LengthUnit extends Unit {
  public static final String concept = "sr.si.structure.LengthUnit";

  public LengthUnit(SNode node) {
    super(node);
  }

  public static LengthUnit newInstance(SModel sm, boolean init) {
    return (LengthUnit) SModelUtil_new.instantiateConceptDeclaration("sr.si.structure.LengthUnit", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static LengthUnit newInstance(SModel sm) {
    return LengthUnit.newInstance(sm, false);
  }
}
