package sr.si.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Meter extends LengthUnit {
  public static final String concept = "sr.si.structure.Meter";

  public Meter(SNode node) {
    super(node);
  }

  public static Meter newInstance(SModel sm, boolean init) {
    return (Meter) SModelUtil_new.instantiateConceptDeclaration("sr.si.structure.Meter", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Meter newInstance(SModel sm) {
    return Meter.newInstance(sm, false);
  }
}
