package sr.si.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Newton extends ForceUnit implements IReducableUnit {
  public static final String concept = "sr.si.structure.Newton";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public Newton(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(Newton.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Newton.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Newton.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Newton.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Newton.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Newton.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(Newton.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, Newton.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, Newton.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(Newton.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, Newton.SMODEL_ATTRIBUTE, node);
  }

  public static Newton newInstance(SModel sm, boolean init) {
    return (Newton) SModelUtil_new.instantiateConceptDeclaration("sr.si.structure.Newton", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Newton newInstance(SModel sm) {
    return Newton.newInstance(sm, false);
  }
}
