package sr.si.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Pascal extends PressureUnit implements IReducableUnit {
  public static final String concept = "sr.si.structure.Pascal";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public Pascal(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(Pascal.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Pascal.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Pascal.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Pascal.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Pascal.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Pascal.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(Pascal.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, Pascal.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, Pascal.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(Pascal.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, Pascal.SMODEL_ATTRIBUTE, node);
  }

  public static Pascal newInstance(SModel sm, boolean init) {
    return (Pascal) SModelUtil_new.instantiateConceptDeclaration("sr.si.structure.Pascal", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Pascal newInstance(SModel sm) {
    return Pascal.newInstance(sm, false);
  }
}
