package sr.si.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PressureUnit extends Unit {
  public static final String concept = "sr.si.structure.PressureUnit";

  public PressureUnit(SNode node) {
    super(node);
  }

  public static PressureUnit newInstance(SModel sm, boolean init) {
    return (PressureUnit) SModelUtil_new.instantiateConceptDeclaration("sr.si.structure.PressureUnit", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static PressureUnit newInstance(SModel sm) {
    return PressureUnit.newInstance(sm, false);
  }
}
