package sr.si.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Si_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("e3b1568d-032f-42dc-8134-000ab9b7e40f(sr.si)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
