package sr.si.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TimeUnit extends Unit {
  public static final String concept = "sr.si.structure.TimeUnit";

  public TimeUnit(SNode node) {
    super(node);
  }

  public static TimeUnit newInstance(SModel sm, boolean init) {
    return (TimeUnit) SModelUtil_new.instantiateConceptDeclaration("sr.si.structure.TimeUnit", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TimeUnit newInstance(SModel sm) {
    return TimeUnit.newInstance(sm, false);
  }
}
