package sr.si.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Unit extends BaseConcept {
  public static final String concept = "sr.si.structure.Unit";

  public Unit(SNode node) {
    super(node);
  }

  public static Unit newInstance(SModel sm, boolean init) {
    return (Unit) SModelUtil_new.instantiateConceptDeclaration("sr.si.structure.Unit", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Unit newInstance(SModel sm) {
    return Unit.newInstance(sm, false);
  }
}
