package sr.si.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class WeightUnit extends Unit {
  public static final String concept = "sr.si.structure.WeightUnit";

  public WeightUnit(SNode node) {
    super(node);
  }

  public static WeightUnit newInstance(SModel sm, boolean init) {
    return (WeightUnit) SModelUtil_new.instantiateConceptDeclaration("sr.si.structure.WeightUnit", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static WeightUnit newInstance(SModel sm) {
    return WeightUnit.newInstance(sm, false);
  }
}
