package de.itemis.tex.ll.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Ll_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("72bf1122-02c6-4129-87a6-f08a4c73f53d(de.itemis.tex.ll)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
