package de.itemis.tex.ll.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TexDirective extends BaseConcept {
  public static final String concept = "de.itemis.tex.ll.structure.TexDirective";

  public TexDirective(SNode node) {
    super(node);
  }

  public static TexDirective newInstance(SModel sm, boolean init) {
    return (TexDirective) SModelUtil_new.instantiateConceptDeclaration("de.itemis.tex.ll.structure.TexDirective", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TexDirective newInstance(SModel sm) {
    return TexDirective.newInstance(sm, false);
  }
}
