package de.itemis.tex.ll.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TexGroup extends TexDirective {
  public static final String concept = "de.itemis.tex.ll.structure.TexGroup";
  public static final String CHILDREN = "children";

  public TexGroup(SNode node) {
    super(node);
  }

  public int getChildrensCount() {
    return this.getChildCount(TexGroup.CHILDREN);
  }

  public Iterator<TexDirective> childrens() {
    return this.children(TexDirective.class, TexGroup.CHILDREN);
  }

  public List<TexDirective> getChildrens() {
    return this.getChildren(TexDirective.class, TexGroup.CHILDREN);
  }

  public void addChildren(TexDirective node) {
    this.addChild(TexGroup.CHILDREN, node);
  }

  public void insertChildren(TexDirective prev, TexDirective node) {
    this.insertChild(prev, TexGroup.CHILDREN, node);
  }

  public static TexGroup newInstance(SModel sm, boolean init) {
    return (TexGroup) SModelUtil_new.instantiateConceptDeclaration("de.itemis.tex.ll.structure.TexGroup", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TexGroup newInstance(SModel sm) {
    return TexGroup.newInstance(sm, false);
  }
}
