package de.itemis.tex.ll.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TexHeaderCommand extends TexHeaderAttribute implements INamedConcept {
  public static final String concept = "de.itemis.tex.ll.structure.TexHeaderCommand";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public TexHeaderCommand(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(TexHeaderCommand.NAME);
  }

  public void setName(String value) {
    this.setProperty(TexHeaderCommand.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(TexHeaderCommand.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(TexHeaderCommand.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(TexHeaderCommand.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(TexHeaderCommand.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(TexHeaderCommand.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(TexHeaderCommand.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(TexHeaderCommand.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, TexHeaderCommand.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, TexHeaderCommand.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(TexHeaderCommand.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, TexHeaderCommand.SMODEL_ATTRIBUTE, node);
  }

  public static TexHeaderCommand newInstance(SModel sm, boolean init) {
    return (TexHeaderCommand) SModelUtil_new.instantiateConceptDeclaration("de.itemis.tex.ll.structure.TexHeaderCommand", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TexHeaderCommand newInstance(SModel sm) {
    return TexHeaderCommand.newInstance(sm, false);
  }
}
