package de.itemis.tex.ll.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TexSimpleDirWithText extends TexSimpleDirective {
  public static final String concept = "de.itemis.tex.ll.structure.TexSimpleDirWithText";
  public static final String TEXT = "text";

  public TexSimpleDirWithText(SNode node) {
    super(node);
  }

  public String getText() {
    return this.getProperty(TexSimpleDirWithText.TEXT);
  }

  public void setText(String value) {
    this.setProperty(TexSimpleDirWithText.TEXT, value);
  }

  public static TexSimpleDirWithText newInstance(SModel sm, boolean init) {
    return (TexSimpleDirWithText) SModelUtil_new.instantiateConceptDeclaration("de.itemis.tex.ll.structure.TexSimpleDirWithText", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TexSimpleDirWithText newInstance(SModel sm) {
    return TexSimpleDirWithText.newInstance(sm, false);
  }
}
