package de.itemis.tex.ll.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TextMultiDirective extends TexDirective {
  public static final String concept = "de.itemis.tex.ll.structure.TextMultiDirective";
  public static final String ELEMENTS = "elements";

  public TextMultiDirective(SNode node) {
    super(node);
  }

  public int getElementsesCount() {
    return this.getChildCount(TextMultiDirective.ELEMENTS);
  }

  public Iterator<TextMultiElement> elementses() {
    return this.children(TextMultiElement.class, TextMultiDirective.ELEMENTS);
  }

  public List<TextMultiElement> getElementses() {
    return this.getChildren(TextMultiElement.class, TextMultiDirective.ELEMENTS);
  }

  public void addElements(TextMultiElement node) {
    this.addChild(TextMultiDirective.ELEMENTS, node);
  }

  public void insertElements(TextMultiElement prev, TextMultiElement node) {
    this.insertChild(prev, TextMultiDirective.ELEMENTS, node);
  }

  public static TextMultiDirective newInstance(SModel sm, boolean init) {
    return (TextMultiDirective) SModelUtil_new.instantiateConceptDeclaration("de.itemis.tex.ll.structure.TextMultiDirective", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TextMultiDirective newInstance(SModel sm) {
    return TextMultiDirective.newInstance(sm, false);
  }
}
