package de.itemis.tex.ll.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TextMultiElement extends BaseConcept {
  public static final String concept = "de.itemis.tex.ll.structure.TextMultiElement";
  public static final String TEXT = "text";

  public TextMultiElement(SNode node) {
    super(node);
  }

  public String getText() {
    return this.getProperty(TextMultiElement.TEXT);
  }

  public void setText(String value) {
    this.setProperty(TextMultiElement.TEXT, value);
  }

  public static TextMultiElement newInstance(SModel sm, boolean init) {
    return (TextMultiElement) SModelUtil_new.instantiateConceptDeclaration("de.itemis.tex.ll.structure.TextMultiElement", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TextMultiElement newInstance(SModel sm) {
    return TextMultiElement.newInstance(sm, false);
  }
}
