package de.itemis.tex.ll.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class TexContainerDirective_Constraints extends BaseConstraintsDescriptor {
  public TexContainerDirective_Constraints() {
    super("de.itemis.tex.ll.structure.TexContainerDirective");
  }
}
