package sr.functionblocks.rt.main;

/*Generated by MPS */


public class DoubleComparer {
  public DoubleComparer() {
  }

  public static boolean isSame(double d1, double d2) {
    return isSame(d1, d2, 0.0001);
  }

  public static boolean isSame(double d1, double d2, double delta) {
    return Math.abs(d1 - d2) <= delta;
  }
}
