package sr.functionblocks.rt.main;

/*Generated by MPS */


public class TestFailedException extends Exception {
  public TestFailedException() {
  }

  public TestFailedException(String message) {
    super(message);
  }
}
