package sr.functionblocks.rt.main;

/*Generated by MPS */


public class ValueSetContainer {
  private Value[] values;
  private ValueSetContainer[] children;

  public ValueSetContainer(Value... values) {
    this.values = values;
  }

  public Object getFor(String symname) {
    for (Value v : values) {
      if (v.isFor(symname)) {
        return v.getValue();
      }
    }
    if (children != null) {
      for (ValueSetContainer c : children) {
        Object t = c.getFor(symname);
        if (t != null) {
          return t;
        }
      }
    }
    return null;
  }

  public void setChildren(ValueSetContainer[] children) {
    this.children = children;
  }

  public static ValueSetContainer createForAll(ValueSetContainer... containers) {
    ValueSetContainer c = new ValueSetContainer();
    c.setChildren(containers);
    return c;
  }
}
