package de.itemis.tex.ll.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"de.itemis.tex.ll.structure.TexContainerDirective", "de.itemis.tex.ll.structure.TexGroup", "de.itemis.tex.ll.structure.TexHeader", "de.itemis.tex.ll.structure.TexHeaderCommand", "de.itemis.tex.ll.structure.TexNewLine", "de.itemis.tex.ll.structure.TexResource", "de.itemis.tex.ll.structure.TexSimpleDirWithText", "de.itemis.tex.ll.structure.TexSimpleDirective", "de.itemis.tex.ll.structure.TextMultiDirective", "de.itemis.tex.ll.structure.TextMultiElement", "de.itemis.tex.ll.structure.TextOnlyDirective"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 5:
        return new TexResource_BehaviorDescriptor();
      case 7:
        return new TexSimpleDirective_BehaviorDescriptor();
      case 6:
        return new TexSimpleDirWithText_BehaviorDescriptor();
      case 0:
        return new TexContainerDirective_BehaviorDescriptor();
      case 2:
        return new TexHeader_BehaviorDescriptor();
      case 3:
        return new TexHeaderCommand_BehaviorDescriptor();
      case 10:
        return new TextOnlyDirective_BehaviorDescriptor();
      case 1:
        return new TexGroup_BehaviorDescriptor();
      case 4:
        return new TexNewLine_BehaviorDescriptor();
      case 8:
        return new TextMultiDirective_BehaviorDescriptor();
      case 9:
        return new TextMultiElement_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
