package de.itemis.tex.ll.behavior;

/*Generated by MPS */


public class TexContainerDirective_BehaviorDescriptor extends TexDirective_BehaviorDescriptor {
  public TexContainerDirective_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.itemis.tex.ll.structure.TexContainerDirective";
  }
}
