package de.itemis.tex.ll.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class TexContainerDirective_Behavior {
  public static void init(SNode thisNode) {
    SNode opheader = SConceptOperations.createNewNode("de.itemis.tex.ll.structure.TexHeader", null);
    SPropertyOperations.set(opheader, "name", "begin");
    SLinkOperations.setTarget(thisNode, "opening", opheader, true);

    SNode clheader = SConceptOperations.createNewNode("de.itemis.tex.ll.structure.TexHeader", null);
    SPropertyOperations.set(clheader, "name", "end");
    SLinkOperations.setTarget(thisNode, "closing", clheader, true);
  }
}
