package de.itemis.tex.ll.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class TexDirective_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TexDirective_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.itemis.tex.ll.structure.TexDirective";
  }
}
