package de.itemis.tex.ll.behavior;

/*Generated by MPS */


public class TexGroup_BehaviorDescriptor extends TexDirective_BehaviorDescriptor {
  public TexGroup_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.itemis.tex.ll.structure.TexGroup";
  }
}
