package de.itemis.tex.ll.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class TexHeaderAttribute_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TexHeaderAttribute_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.itemis.tex.ll.structure.TexHeaderAttribute";
  }
}
