package de.itemis.tex.ll.behavior;

/*Generated by MPS */


public class TexNewLine_BehaviorDescriptor extends TexDirective_BehaviorDescriptor {
  public TexNewLine_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.itemis.tex.ll.structure.TexNewLine";
  }
}
