package de.itemis.tex.ll.behavior;

/*Generated by MPS */


public class TexSimpleDirective_BehaviorDescriptor extends TexDirective_BehaviorDescriptor {
  public TexSimpleDirective_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.itemis.tex.ll.structure.TexSimpleDirective";
  }
}
