package de.itemis.tex.ll.behavior;

/*Generated by MPS */


public class TexSimpleDirWithText_BehaviorDescriptor extends TexSimpleDirective_BehaviorDescriptor {
  public TexSimpleDirWithText_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.itemis.tex.ll.structure.TexSimpleDirWithText";
  }
}
