package de.itemis.tex.ll.behavior;

/*Generated by MPS */


public class TextMultiDirective_BehaviorDescriptor extends TexDirective_BehaviorDescriptor {
  public TextMultiDirective_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.itemis.tex.ll.structure.TextMultiDirective";
  }
}
