package de.itemis.tex.ll.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class TextMultiElement_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TextMultiElement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.itemis.tex.ll.structure.TextMultiElement";
  }
}
