package de.itemis.tex.ll.behavior;

/*Generated by MPS */


public class TextOnlyDirective_BehaviorDescriptor extends TexDirective_BehaviorDescriptor {
  public TextOnlyDirective_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.itemis.tex.ll.structure.TextOnlyDirective";
  }
}
