package de.itemis.tex.ll.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.textGen.TextGenManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class TexContainerDirective_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    TextGenManager.instance().appendNodeText(this.getContext(), this.getBuffer(), SLinkOperations.getTarget(node, "opening", true), this.getSNode());
    this.appendNewLine();
    this.increaseDepth();
    if (ListSequence.fromList(SLinkOperations.getTargets(node, "children", true)).isNotEmpty()) {
      for (SNode item : SLinkOperations.getTargets(node, "children", true)) {
        TextGenManager.instance().appendNodeText(this.getContext(), this.getBuffer(), item, this.getSNode());
      }
    }
    this.decreaseDepth();
    TextGenManager.instance().appendNodeText(this.getContext(), this.getBuffer(), SLinkOperations.getTarget(node, "closing", true), this.getSNode());
    this.appendNewLine();
  }
}
