package de.itemis.tex.ll.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.textGen.TextGenManager;

public class TexResource_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    if (ListSequence.fromList(SLinkOperations.getTargets(node, "directives", true)).isNotEmpty()) {
      for (SNode item : SLinkOperations.getTargets(node, "directives", true)) {
        TextGenManager.instance().appendNodeText(this.getContext(), this.getBuffer(), item, this.getSNode());
      }
    }
  }

  public String getExtension(SNode node) {
    return "tex";
  }
}
