package jetbrains.mps.baselanguage.dispatch.rt;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public abstract class ExpressionStatementWrapper<T> {
  public ExpressionStatementWrapper() {
  }

  public abstract T apply(SNode ex);
}
