package sr.functionblocks.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.PropertyMacroContext;
import sr.functionblocks.behavior.Block_Behavior;
import sr.functionblocks.behavior.Symbol_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import sr.functionblocks.behavior.FunctionSymbol_Behavior;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import sr.functionblocks.interpreter.TypeHelper;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import sr.functionblocks.behavior.FunctionBlock_Behavior;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;

public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_3006277004735706769(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return Block_Behavior.call_javaName_3006277004735707306(_context.getNode()) + "_Implementation";
  }

  public static Object propertyMacro_GetPropertyValue_3893397118698887688(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return Symbol_Behavior.call_qualifiedName_3006277004735674470(_context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_3893397118698840060(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return Symbol_Behavior.call_qualifiedJavaName_3006277004735708832(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "symbol", true), "symbol", false));
  }

  public static Object propertyMacro_GetPropertyValue_3893397118698882633(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SNodeOperations.getAncestor(_context.getNode(), "sr.functionblocks.structure.FunctionSymbol", false, false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_3893397118698829040(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return FunctionSymbol_Behavior.call_testMethodName_3893397118698831637(_context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_3006277004735868585(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return Symbol_Behavior.call_qualifiedJavaName_3006277004735708832(_context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_3006277004735868561(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return Symbol_Behavior.call_qualifiedJavaName_3006277004735708832(_context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_3893397118698827405(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return Symbol_Behavior.call_qualifiedJavaName_3006277004735708832(_context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_3893397118698827575(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return Symbol_Behavior.call_qualifiedJavaName_3006277004735708832(_context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_3006277004735708510(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_3006277004735712202(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return Block_Behavior.call_javaName_3006277004735707306(_context.getNode()) + "_Implementation";
  }

  public static Object propertyMacro_GetPropertyValue_3006277004735719175(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return Symbol_Behavior.call_qualifiedJavaName_3006277004735708832(SLinkOperations.getTarget(_context.getNode(), "symbol", false));
  }

  public static Object propertyMacro_GetPropertyValue_3893397118698818635(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_3893397118698879293(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "block", false), "name");
  }

  public static Object referenceMacro_GetReferent_3893397118698831670(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return FunctionSymbol_Behavior.call_testMethodName_3893397118698831637(_context.getNode());
  }

  public static Object referenceMacro_GetReferent_3893397118698827655(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getOutputNodeByInputNodeAndMappingLabel(FunctionSymbol_Behavior.call_owningBlock_3006277004735845605(SNodeOperations.cast(_context.getNode(), "sr.functionblocks.structure.FunctionSymbol")), "block2class"), "constructor", true)).first();
  }

  public static Object referenceMacro_GetReferent_3893397118698827672(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SNodeOperations.cast(_context.getNode(), "sr.functionblocks.structure.FunctionSymbol"), "function2method");
  }

  public static Object referenceMacro_GetReferent_3006277004735875129(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return Symbol_Behavior.call_qualifiedJavaName_3006277004735708832(SLinkOperations.getTarget(_context.getNode(), "symbol", false));
  }

  public static Object referenceMacro_GetReferent_3006277004735845584(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getOutputNodeByInputNodeAndMappingLabel(FunctionSymbol_Behavior.call_owningBlock_3006277004735845605(SLinkOperations.getTarget(_context.getNode(), "function", false)), "block2class"), "constructor", true)).first();
  }

  public static Object referenceMacro_GetReferent_3006277004735845623(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), "function", false), "function2method");
  }

  public static Object referenceMacro_GetReferent_3893397118698823133(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "valueSet", false), "name");
  }

  public static Object referenceMacro_GetReferent_3893397118698879272(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), "block", false), "block2class"), "constructor", true)).first();
  }

  public static boolean ifMacro_Condition_3893397118698887702(final IOperationContext operationContext, final IfMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "testBlock", true) == null || (int) ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(_context.getNode(), "testBlock", true), "tests", true)).count() == 0;
  }

  public static boolean ifMacro_Condition_3893397118698836914(final IOperationContext operationContext, final IfMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "testBlock", true) != null;
  }

  public static SNode sourceNodeQuery_3893397118698840099(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "value", true);
  }

  public static SNode sourceNodeQuery_3893397118698882600(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "expectedResult", true);
  }

  public static SNode sourceNodeQuery_3006277004735709784(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "javaType", true);
  }

  public static SNode sourceNodeQuery_3006277004735877231(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "javaType", true);
  }

  public static SNode sourceNodeQuery_3006277004735868616(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return TypeHelper.boxedType(SLinkOperations.getTarget(_context.getNode(), "javaType", true));
  }

  public static SNode sourceNodeQuery_3893397118698827398(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "javaType", true);
  }

  public static SNode sourceNodeQuery_3893397118698827757(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return TypeHelper.boxedType(SLinkOperations.getTarget(_context.getNode(), "javaType", true));
  }

  public static SNode sourceNodeQuery_3893397118698827644(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return TypeHelper.boxedType(SLinkOperations.getTarget(_context.getNode(), "javaType", true));
  }

  public static SNode sourceNodeQuery_3006277004735709795(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "expr", true), "expression", true);
  }

  public static SNode sourceNodeQuery_3006277004735714842(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "value", true);
  }

  public static Iterable sourceNodesQuery_3893397118698831667(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return FunctionBlock_Behavior.call_functions_3893397118698831680(_context.getNode());
  }

  public static Iterable sourceNodesQuery_3006277004735708464(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "contents", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.isInstanceOf(it, "sr.functionblocks.structure.FunctionSymbol");
      }
    });
  }

  public static Iterable sourceNodesQuery_3893397118698840043(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "values", true);
  }

  public static Iterable sourceNodesQuery_3893397118698840026(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SLinkOperations.getTarget(_context.getNode(), "testBlock", true), "tests", true);
  }

  public static Iterable sourceNodesQuery_3006277004735868549(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(FunctionSymbol_Behavior.call_referencedSymbols_3006277004735708695(_context.getNode())).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.isInstanceOf(it, "sr.functionblocks.structure.EnvSymbol");
      }
    });
  }

  public static Iterable sourceNodesQuery_3893397118698827451(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(FunctionSymbol_Behavior.call_referencedSymbols_3006277004735708695(_context.getNode())).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.isInstanceOf(it, "sr.functionblocks.structure.FunctionSymbol");
      }
    });
  }

  public static Iterable sourceNodesQuery_3893397118698827601(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(FunctionSymbol_Behavior.call_referencedSymbols_3006277004735708695(_context.getNode())).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.isInstanceOf(it, "sr.functionblocks.structure.FunctionSymbol");
      }
    });
  }

  public static Iterable sourceNodesQuery_3006277004735714788(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "values", true);
  }

  public static Iterable sourceNodesQuery_3006277004735874174(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "values", true);
  }
}
