package de.itemis.tex.ll.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.SModelReference;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("de.itemis.tex.ll", "72bf1122-02c6-4129-87a6-f08a4c73f53d"), SModelReference.fromString("r:309849a8-b7c1-44bd-9ba1-c9e69454f444(de.itemis.tex.ll.intentions)"));
  }

  public void init() {
    add(new addCommand_Intention(), "2194098664609132895");
  }
}
